# AUTOGenerated for remove_window
link_method_documentation 'Command.remove_window', 
	'Your description',
 	{
		:id => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.remove_window' 

# AUTOGenerated for remove_all_windows
link_method_documentation 'Command.remove_all_windows', 
	'Your description',
 	{}, true # Maybe changed
register_command :standard, 'Command.remove_all_windows' 

# AUTOGenerated for close_window
link_method_documentation 'Command.close_window', 
	'Your description',
 	{
		:id => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.close_window' 

# AUTOGenerated for open_window
link_method_documentation 'Command.open_window', 
	'Your description',
 	{
		:id => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.open_window' 

# AUTOGenerated for bind
link_method_documentation 'Command.bind', 
	'Your description',
 	{
		:e => ["Args description", :ArgType],
		:k => ["Args description", :ArgType],
		:"*n" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.bind' 

# AUTOGenerated for unbind
link_method_documentation 'Command.unbind', 
	'Your description',
 	{
		:e => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.unbind' 

