# AUTOGenerated for delete_save
link_method_documentation 'Command.delete_save', 
	'Your description',
 	{
		:index => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.delete_save' 

# AUTOGenerated for monser_defense
link_method_documentation 'Command.monser_defense', 
	'Your description',
 	{
		:id => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.monser_defense' 

# AUTOGenerated for monster_hp
link_method_documentation 'Command.monster_hp', 
	'Your description',
 	{
		:id => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.monster_hp' 

# AUTOGenerated for events_collide?
link_method_documentation 'Command.events_collide?', 
	'Your description',
 	{
		:ev1 => ["Args description", :ArgType],
		:ev2 => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.events_collide?' 

# AUTOGenerated for collide?
link_method_documentation 'Command.collide?', 
	'Your description',
 	{
		:ev1 => ["Args description", :ArgType],
		:ev2 => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.collide?' 

# AUTOGenerated for look_at
link_method_documentation 'Command.look_at', 
	'Your description',
 	{
		:ev => ["Args description", :ArgType],
		:to => ["Args description", :ArgType],
		:scope => ["Args description", :ArgType],
		:"*metric" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.look_at' 

# AUTOGenerated for look_at?
link_method_documentation 'Command.look_at?', 
	'Your description',
 	{
		:ev => ["Args description", :ArgType],
		:to => ["Args description", :ArgType],
		:scope => ["Args description", :ArgType],
		:"*metric" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.look_at?' 

# AUTOGenerated for actor_experience
link_method_documentation 'Command.actor_experience', 
	'Your description',
 	{
		:id => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.actor_experience' 

# AUTOGenerated for actor_exp_rate
link_method_documentation 'Command.actor_exp_rate', 
	'Your description',
 	{
		:id => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.actor_exp_rate' 

# AUTOGenerated for actor_magic
link_method_documentation 'Command.actor_magic', 
	'Your description',
 	{
		:id => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.actor_magic' 

# AUTOGenerated for key_number
link_method_documentation 'Command.key_number', 
	'Your description',
 	{}, true # Maybe changed
register_command :standard, 'Command.key_number' 

# AUTOGenerated for windows_username
link_method_documentation 'Command.windows_username', 
	'Your description',
 	{}, true # Maybe changed
register_command :standard, 'Command.windows_username' 

# AUTOGenerated for bind
link_method_documentation 'Command.bind', 
	'Your description',
 	{
		:e => ["Args description", :ArgType],
		:"*args" => ["Args description", :ArgType],
		:"&block" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.bind' 

# AUTOGenerated for unbind
link_method_documentation 'Command.unbind', 
	'Your description',
 	{
		:e => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.unbind' 

# AUTOGenerated for mouse_hover_player?
link_method_documentation 'Command.mouse_hover_player?', 
	'Your description',
 	{}, true # Maybe changed
register_command :standard, 'Command.mouse_hover_player?' 

# AUTOGenerated for mouse_click_player?
link_method_documentation 'Command.mouse_click_player?', 
	'Your description',
 	{}, true # Maybe changed
register_command :standard, 'Command.mouse_click_player?' 

# AUTOGenerated for mouse_press_player?
link_method_documentation 'Command.mouse_press_player?', 
	'Your description',
 	{
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_press_player?' 

# AUTOGenerated for mouse_trigger_player?
link_method_documentation 'Command.mouse_trigger_player?', 
	'Your description',
 	{
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_trigger_player?' 

# AUTOGenerated for mouse_repeat_player?
link_method_documentation 'Command.mouse_repeat_player?', 
	'Your description',
 	{
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_repeat_player?' 

# AUTOGenerated for mouse_release_player?
link_method_documentation 'Command.mouse_release_player?', 
	'Your description',
 	{
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_release_player?' 

