# AUTOGenerated for create_rect_area
link_method_documentation 'Command.create_rect_area', 
	'Your description',
 	{
		:x => ["Args description", :ArgType],
		:y => ["Args description", :ArgType],
		:width => ["Args description", :ArgType],
		:height => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.create_rect_area' 

# AUTOGenerated for create_circle_area
link_method_documentation 'Command.create_circle_area', 
	'Your description',
 	{
		:x => ["Args description", :ArgType],
		:y => ["Args description", :ArgType],
		:rayon => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.create_circle_area' 

# AUTOGenerated for create_ellipse_area
link_method_documentation 'Command.create_ellipse_area', 
	'Your description',
 	{
		:x => ["Args description", :ArgType],
		:y => ["Args description", :ArgType],
		:width => ["Args description", :ArgType],
		:height => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.create_ellipse_area' 

# AUTOGenerated for create_polygon_area
link_method_documentation 'Command.create_polygon_area', 
	'Your description',
 	{
		:"*points" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.create_polygon_area' 

# AUTOGenerated for in_area?
link_method_documentation 'Command.in_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:x => ["Args description", :ArgType],
		:y => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.in_area?' 

# AUTOGenerated for mouse_hover_area?
link_method_documentation 'Command.mouse_hover_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_hover_area?' 

# AUTOGenerated for mouse_hover_square_area?
link_method_documentation 'Command.mouse_hover_square_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_hover_square_area?' 

# AUTOGenerated for mouse_click_area?
link_method_documentation 'Command.mouse_click_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_click_area?' 

# AUTOGenerated for mouse_click_square_area?
link_method_documentation 'Command.mouse_click_square_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_click_square_area?' 

# AUTOGenerated for mouse_trigger_area?
link_method_documentation 'Command.mouse_trigger_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_trigger_area?' 

# AUTOGenerated for mouse_trigger_square_area?
link_method_documentation 'Command.mouse_trigger_square_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_trigger_square_area?' 

# AUTOGenerated for mouse_press_area?
link_method_documentation 'Command.mouse_press_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_press_area?' 

# AUTOGenerated for mouse_press_square_area?
link_method_documentation 'Command.mouse_press_square_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_press_square_area?' 

# AUTOGenerated for mouse_release_area?
link_method_documentation 'Command.mouse_release_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_release_area?' 

# AUTOGenerated for mouse_release_square_area?
link_method_documentation 'Command.mouse_release_square_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_release_square_area?' 

# AUTOGenerated for mouse_repeat_area?
link_method_documentation 'Command.mouse_repeat_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_repeat_area?' 

# AUTOGenerated for mouse_repeat_square_area?
link_method_documentation 'Command.mouse_repeat_square_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_repeat_square_area?' 

# AUTOGenerated for mouse_square_hover_area?
link_method_documentation 'Command.mouse_square_hover_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_square_hover_area?' 

# AUTOGenerated for mouse_clicked_area?
link_method_documentation 'Command.mouse_clicked_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_clicked_area?' 

# AUTOGenerated for mouse_square_clicked_area?
link_method_documentation 'Command.mouse_square_clicked_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_square_clicked_area?' 

# AUTOGenerated for mouse_triggered_area?
link_method_documentation 'Command.mouse_triggered_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_triggered_area?' 

# AUTOGenerated for mouse_square_triggered_area?
link_method_documentation 'Command.mouse_square_triggered_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_square_triggered_area?' 

# AUTOGenerated for mouse_pressed_area?
link_method_documentation 'Command.mouse_pressed_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_pressed_area?' 

# AUTOGenerated for mouse_square_pressed_area?
link_method_documentation 'Command.mouse_square_pressed_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_square_pressed_area?' 

# AUTOGenerated for mouse_released_area?
link_method_documentation 'Command.mouse_released_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_released_area?' 

# AUTOGenerated for mouse_square_released_area?
link_method_documentation 'Command.mouse_square_released_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_square_released_area?' 

# AUTOGenerated for mouse_repeated_area?
link_method_documentation 'Command.mouse_repeated_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_repeated_area?' 

# AUTOGenerated for mouse_square_repeat_area?
link_method_documentation 'Command.mouse_square_repeat_area?', 
	'Your description',
 	{
		:area => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.mouse_square_repeat_area?' 

# AUTOGenerated for bind
link_method_documentation 'Command.bind', 
	'Your description',
 	{
		:e => ["Args description", :ArgType],
		:"*args" => ["Args description", :ArgType],
		:"&block" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.bind' 

# AUTOGenerated for unbind
link_method_documentation 'Command.unbind', 
	'Your description',
 	{
		:e => ["Args description", :ArgType],
		:"*k" => ["Args description", :ArgType],

	}, true # Maybe changed
register_command :standard, 'Command.unbind' 

